server:
  port: 9090

spring:
  application:
    name: mini-commerce
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/mini-commerce?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 'jylim1104'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      connection-timeout: 5000
      connection-init-sql: select 1
      auto-commit: false

  #JPA
  jpa:
    show_sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Logging
logging:
  config: classpath:logback-local.xml